const deploymentGuards = [
  "no-secret-values-in-manifest",
  "durable-store-required",
  "auth-token-required",
  "rate-limit-policy-required",
  "structured-logging-required",
  "metrics-and-alerts-required",
];

const services = [
  {
    id: "indexer",
    label: "Private Pool v2 Indexer",
    requiredSecrets: [
      "VANTA_PRIVATE_POOL_V2_INDEXER_DATABASE_URL",
      "VANTA_PRIVATE_POOL_V2_INDEXER_AUTH_TOKEN",
      "VANTA_PRIVATE_POOL_V2_INDEXER_RPC_URL",
    ],
    requiredStorage: ["commitments", "merkle_roots", "nullifiers", "indexer_cursors"],
    health: ["/health", "/v1/roots/latest"],
    readiness: ["/v1/commitments", "/v1/nullifiers/:nullifier", "/v1/private-sends"],
    deploymentGuards,
  },
  {
    id: "relayer",
    label: "Private Pool v2 Relayer",
    requiredSecrets: [
      "VANTA_PRIVATE_POOL_V2_RELAYER_DATABASE_URL",
      "VANTA_PRIVATE_POOL_V2_RELAYER_AUTH_TOKEN",
      "VANTA_PRIVATE_POOL_V2_RELAYER_FEE_WALLET",
      "VANTA_PRIVATE_POOL_V2_RELAYER_RPC_URL",
      "VANTA_PRIVATE_POOL_V2_RELAYER_SOLANA_SUBMISSION_MODE",
      "VANTA_PRIVATE_POOL_V2_RELAYER_FEE_PAYER_KEYPAIR_JSON",
      "VANTA_PRIVATE_POOL_V2_RELAYER_SOLANA_SUBMIT_ACK",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_PROGRAM_ID",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_POOL_STATE",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_NULLIFIER_SET",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_OUTPUT_QUEUE",
    ],
    requiredStorage: ["claim_quotes", "claim_submissions", "relayer_idempotency_keys"],
    health: ["/health", "/v1/claims/quote"],
    readiness: ["/v1/claims/quote", "/v1/claims/submit"],
    deploymentGuards,
  },
  {
    id: "prover",
    label: "Private Pool v2 Prover",
    requiredSecrets: [
      "VANTA_PRIVATE_POOL_V2_PROVER_AUTH_TOKEN",
      "VANTA_PRIVATE_POOL_V2_PROVER_ARTIFACT_PATH",
      "VANTA_PRIVATE_POOL_V2_PROVER_KEYSET",
    ],
    requiredStorage: ["proof_jobs", "proof_artifacts", "verifying_key_snapshots"],
    health: ["/health", "/v1/proofs/health"],
    readiness: ["/v1/proofs", "/v1/proofs/verify"],
    deploymentGuards,
  },
  {
    id: "verifier",
    label: "Private Pool v2 Verifier Registry",
    requiredSecrets: [
      "VANTA_PRIVATE_POOL_V2_VERIFIER_DATABASE_URL",
      "VANTA_PRIVATE_POOL_V2_VERIFIER_AUTH_TOKEN",
      "VANTA_PRIVATE_POOL_V2_VERIFIER_KEYSET",
    ],
    requiredStorage: ["accepted_receipts", "verified_public_inputs", "claim_nullifiers"],
    health: ["/health", "/v1/proofs/accept"],
    readiness: ["/v1/proofs/accept"],
    deploymentGuards,
  },
  {
    id: "operator",
    label: "Vanta Operator Gateway",
    requiredSecrets: [
      "VANTA_PRIVATE_POOL_V2_DATABASE_URL",
      "VANTA_PRIVATE_POOL_V2_OPERATOR_AUTH_TOKEN",
      "VANTA_PRIVATE_POOL_V2_INDEXER_URL",
      "VANTA_PRIVATE_POOL_V2_PROVER_URL",
      "VANTA_PRIVATE_POOL_V2_RELAYER_URL",
      "VANTA_PRIVATE_POOL_V2_VERIFIER_URL",
      "VANTA_PRIVATE_POOL_V2_REQUIRE_RELAYER_SERIALIZED_TRANSACTION",
    ],
    requiredStorage: ["protocol_settlements", "operator_idempotency_keys"],
    health: ["/health", "/state/private-pool-v2-status"],
    readiness: ["/state/private-pool-v2-status", "/private-pool-v2/protocol-settlements"],
    deploymentGuards,
  },
];

const serviceEdges = [
  {
    from: "operator",
    to: "indexer",
    purpose: "load commitment roots and verify settlement source state",
    auth: "mutual-service-auth",
    failurePolicy: "fail-closed",
    requiredChecks: ["root-read-health", "commitment-lookup-health"],
  },
  {
    from: "operator",
    to: "prover",
    purpose: "request shield, claim, send, swap, and settlement proofs",
    auth: "mutual-service-auth",
    failurePolicy: "fail-closed",
    requiredChecks: ["proof-job-health", "verifying-key-match"],
  },
  {
    from: "operator",
    to: "verifier",
    purpose: "accept proof receipts and enforce receipt idempotency",
    auth: "mutual-service-auth",
    failurePolicy: "fail-closed",
    requiredChecks: ["proof-rejection-smoke", "receipt-idempotency-smoke"],
  },
  {
    from: "operator",
    to: "relayer",
    purpose: "quote and submit private claim exits",
    auth: "mutual-service-auth",
    failurePolicy: "fail-closed",
    requiredChecks: ["quote-expiry-smoke", "submission-idempotency-smoke"],
  },
  {
    from: "verifier",
    to: "indexer",
    purpose: "confirm roots, nullifiers, and private-send output appends before accepting receipts",
    auth: "mutual-service-auth",
    failurePolicy: "fail-closed",
    requiredChecks: [
      "root-currentness-smoke",
      "nullifier-replay-smoke",
      "private-send-output-append-smoke",
      "private-send-atomic-rejection-smoke",
    ],
  },
  {
    from: "relayer",
    to: "indexer",
    purpose: "load claim roots and reject stale or replayed exits",
    auth: "mutual-service-auth",
    failurePolicy: "fail-closed",
    requiredChecks: ["claim-root-smoke", "claim-nullifier-smoke"],
  },
];

export function createVantaProductionServiceTopology() {
  return {
    version: "vanta-production-service-topology-0.1",
    network: "mainnet-beta",
    blockers: [
      "fresh-deployed-service-health-and-readiness-required",
      "production-secret-manager-required",
      "third-party-security-review-required",
      "mainnet-funds-approval-required",
    ],
    mainnetReady: false,
    productionReady: false,
    releaseGates: [
      "all-service-edges-authenticated",
      "all-service-health-surfaces-green",
      "all-readiness-surfaces-green",
      "all-durable-stores-restored-in-restart-check",
      "all-nullifier-replay-checks-green",
    ],
    requiredVerificationCommands: [
      "npm run mainnet:service-topology-check",
      "npm run mainnet:role-service-replay-status",
      "npm run mainnet:role-service-replay-evidence-check",
      "npm run private-pool-v2:service-network-check",
      "npm run mainnet:service-contract-check",
      "npm run mainnet:deployment-manifest-check",
      "npm run storage:adapter-check",
      "npm run nullifier:replay-guard-check",
    ],
    serviceEdges,
    services,
  };
}
