const forbiddenValues = [
  "private-key",
  "seed-phrase",
  "keypair-file",
  "raw-secret-value",
  "rpc-credential-value",
];

const sharedRotationRequirements = [
  "rotation-runbook-required",
  "emergency-revocation-required",
  "last-rotated-at-tracked",
  "owner-team-tracked",
  "least-privilege-access",
];

const scopes = [
  {
    id: "pay",
    label: "Vanta Pay",
    status: "contracted-not-provisioned",
    allowedSecretRefs: [
      "VANTA_PAY_SECRET_KEY_REF",
      "VANTA_PAY_WEBHOOK_SECRET_REF",
      "VANTA_PAY_INTERNAL_SETTLEMENT_TOKEN_REF",
      "VANTA_PAY_DATABASE_URL_REF",
      "VANTA_PAY_PRIVATE_POOL_OPERATOR_TOKEN_REF",
    ],
    forbiddenValues,
    rotationRequirements: sharedRotationRequirements,
  },
  {
    id: "privatePoolV2",
    label: "Private Pool v2",
    status: "contracted-not-provisioned",
    allowedSecretRefs: [
      "VANTA_PRIVATE_POOL_V2_OPERATOR_TOKEN_REF",
      "VANTA_PRIVATE_POOL_V2_DATABASE_URL_REF",
      "VANTA_INDEXER_AUTH_TOKEN_REF",
      "VANTA_PROVER_AUTH_TOKEN_REF",
      "VANTA_RELAYER_AUTH_TOKEN_REF",
      "VANTA_VERIFIER_AUTH_TOKEN_REF",
      "VANTA_PRIVATE_POOL_V2_INDEXER_DATABASE_URL_REF",
      "VANTA_PRIVATE_POOL_V2_PROVER_DATABASE_URL_REF",
      "VANTA_PRIVATE_POOL_V2_RELAYER_DATABASE_URL_REF",
      "VANTA_PRIVATE_POOL_V2_VERIFIER_DATABASE_URL_REF",
      "VANTA_PRIVATE_POOL_V2_PROVER_ARTIFACT_REF",
      "VANTA_PRIVATE_POOL_V2_RELAYER_FEE_WALLET_REF",
      "VANTA_PRIVATE_POOL_V2_RELAYER_FEE_PAYER_KEYPAIR_JSON_REF",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_PROGRAM_ID_REF",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_POOL_STATE_REF",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_NULLIFIER_SET_REF",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_OUTPUT_QUEUE_REF",
      "VANTA_PRIVATE_POOL_V2_SOLANA_SPEND_AUTHORITY_REF",
    ],
    forbiddenValues,
    rotationRequirements: sharedRotationRequirements,
  },
  {
    id: "strategy",
    label: "Strategy",
    status: "contracted-not-provisioned",
    allowedSecretRefs: [
      "VANTA_STRATEGY_DATABASE_URL_REF",
      "VANTA_STRATEGY_JUPITER_API_KEY_REF",
      "VANTA_STRATEGY_JITO_AUTH_TOKEN_REF",
      "VANTA_STRATEGY_OPERATOR_TOKEN_REF",
    ],
    forbiddenValues,
    rotationRequirements: sharedRotationRequirements,
  },
  {
    id: "swap",
    label: "SOL-to-Shielded Swap Adapter",
    status: "contracted-not-provisioned",
    allowedSecretRefs: [
      "VANTA_SOLANA_RPC_URL_REF",
      "VANTA_SOL_TO_SHIELDED_ADAPTER_AUTH_TOKEN_REF",
      "VANTA_SOL_TO_SHIELDED_JUPITER_API_KEY_REF",
    ],
    forbiddenValues,
    rotationRequirements: sharedRotationRequirements,
  },
  {
    id: "operator",
    label: "Operator Control Plane",
    status: "contracted-not-provisioned",
    allowedSecretRefs: [
      "VANTA_OPERATOR_DATABASE_URL_REF",
      "VANTA_OPERATOR_AUTH_TOKEN_REF",
      "VANTA_OPERATOR_OBSERVABILITY_TOKEN_REF",
      "VANTA_OPERATOR_INCIDENT_WEBHOOK_REF",
    ],
    forbiddenValues,
    rotationRequirements: sharedRotationRequirements,
  },
  {
    id: "turnkey",
    label: "Turnkey Wallet Infrastructure",
    status: "contracted-not-provisioned",
    allowedSecretRefs: [
      "VANTA_TURNKEY_ORGANIZATION_ID_REF",
      "VANTA_TURNKEY_API_PUBLIC_KEY_REF",
      "VANTA_TURNKEY_API_PRIVATE_KEY_REF",
      "VANTA_TURNKEY_SIGN_WITH_REF",
      "VANTA_SOL_TO_SHIELDED_LIQUIDITY_SIGNER_REF",
      "VANTA_SOL_TO_SHIELDED_LIQUIDITY_PUBLIC_KEY_REF",
      "VANTA_SOL_TO_SHIELDED_TURNKEY_REVIEW_PACKET_REF",
      "VANTA_SOL_TO_SHIELDED_TURNKEY_LIVE_SIGNING_APPROVAL_REF",
      "VANTA_TURNKEY_POLICY_ID_REF",
    ],
    forbiddenValues,
    rotationRequirements: [
      "non-root-agent-users-only",
      "root-credentials-human-admin-only",
      "policy-and-activity-approval-reviewed",
      "no-client-bundle-secret-access",
      "emergency-revocation-required",
    ],
  },
  {
    id: "wallet",
    label: "Browser Wallet Boundary",
    status: "contracted-not-provisioned",
    allowedSecretRefs: ["none-browser-wallet-signing-only"],
    forbiddenValues,
    rotationRequirements: ["no-server-wallet-custody", "no-private-key-ingestion", "wallet-standard-only"],
  },
];

const globalRequirements = [
  "secret-manager-required",
  "least-privilege-service-identities",
  "no-secrets-in-repo",
  "no-secrets-in-client-bundles",
  "names-only-in-manifests",
  "rotation-runbook-required",
  "incident-revocation-required",
  "audit-log-secret-access",
  "break-glass-access-reviewed",
  "production-env-values-provisioned-outside-git",
  "tracked-repo-secret-exposure-scan-required",
];

export function createVantaSecretHandlingContract() {
  return {
    version: "vanta-secret-handling-contract-0.1",
    secretReferenceManifestPath: "ops/mainnet/secret-references.manifest.json",
    globalRequirements,
    mainnetReady: false,
    nextImplementationStep:
      "Provision a real production secret manager, map every manifest ref to that manager, and keep staging Render env vars as staging-only references.",
    privateKeyHandling: "never-request-store-or-load-private-keys",
    productionReady: false,
    requiredVerificationCommands: [
      "npm run mainnet:secret-handling-check",
      "npm run mainnet:secret-exposure-check",
      "npm run swap:turnkey-liquidity-signer-dry-run-check",
      "npm run swap:turnkey-liquidity-live-signer-adapter-check",
      "npm run turnkey:integration-contract-check",
      "npm run mainnet:preflight",
      "npm run wallet:signing-safety-check",
    ],
    scopes,
  };
}
