export function createVantaWalletSigningSafetyPolicy() {
  return {
    version: "vanta-wallet-signing-safety-0.1",
    blockedActions: [
      "mainnet-submit-without-explicit-approval",
      "private-key-or-seed-phrase-request",
      "fresh-wallet-server-storage",
      "blind-signing",
      "simulation-bypass",
      "unsigned-transaction-mutation-after-summary",
    ],
    defaultCluster: "mainnet-or-localnet",
    liveMainnetSubmissionEnabled: true,
    mainnetReady: false,
    neverStorePrivateKeys: true,
    releaseGateCommands: [
      "npm run wallet:signing-safety-check",
      "npm run turnkey:integration-contract-check",
      "npm run wallet:browser-signing-safety-check",
      "npm run wallet:fresh-wallet-check",
      "npm run wallet:fresh-wallet-browser-check",
      "npm run wallet:transaction-safety-check",
      "npm run wallet:backed-simulation-check",
      "npm run wallet:live-send-inventory-check",
      "npm run wallet:safe-send-boundary-check",
      "npm run wallet:safe-send-hook-check",
      "npm run mainnet:readiness-check",
      "npm run protocol:browser-check",
    ],
    requiredSummaryFields: [
      "cluster",
      "feePayer",
      "recipient",
      "amount",
      "asset",
      "estimatedFees",
      "instructions",
      "recentBlockhash",
      "simulationResult",
    ],
    requiresExplicitHumanApproval: true,
    requiresSimulationBeforeSignature: true,
    requiresTransactionSummaryBeforeSignature: true,
  };
}
