import type { ComponentProps } from "react";
import type { VantaPrivateCoreStatePanel } from "@/components/VantaPrivateCoreStatePanel";
import type { PrivacyFlowContextValue } from "@/data/context/PrivacyFlowContext";

export type VantaPrivateCoreStatePanelProps = ComponentProps<typeof VantaPrivateCoreStatePanel>;

export type PrivateCoreStatePanelBindings = Pick<
  PrivacyFlowContextValue,
  | "privateCoreHoldState"
  | "privateCoreOperatorBoundaryPrimaryNote"
  | "privateCoreOperatorBoundaryStatusLabel"
  | "privateCoreOperatorConsumeError"
  | "privateCoreOperatorConsumes"
  | "privateCoreOperatorContractMirrorPrimaryNote"
  | "privateCoreOperatorContractMirrorStatusLabel"
  | "privateCoreOperatorContractStateVersion"
  | "privateCoreOperatorContractSummaryVersion"
  | "privateCoreOperatorContractVersion"
  | "privateCoreOperatorCurrentRoot"
  | "privateCoreOperatorCurrentRootLinkedProof"
  | "privateCoreOperatorCurrentRootProofLinkStatus"
  | "privateCoreOperatorLatestConsume"
  | "privateCoreOperatorLatestConsumeProof"
  | "privateCoreOperatorLatestProof"
  | "privateCoreOperatorLatestRelease"
  | "privateCoreOperatorLatestReleaseProof"
  | "privateCoreOperatorLatestRoot"
  | "privateCoreOperatorLatestSend"
  | "privateCoreOperatorLatestSendLinkedProof"
  | "privateCoreOperatorLatestSendProof"
  | "privateCoreOperatorLatestSwap"
  | "privateCoreOperatorLatestSwapLinkedProof"
  | "privateCoreOperatorLatestSwapProof"
  | "privateCoreOperatorNullifierKeyMode"
  | "privateCoreOperatorOwnerAuthorizationDecision"
  | "privateCoreOperatorOwnerAuthorizationDecisionNote"
  | "privateCoreOperatorOwnerAuthorizationMode"
  | "privateCoreOperatorProofConsumeLinkStatus"
  | "privateCoreOperatorProofError"
  | "privateCoreOperatorProofReleaseLinkStatus"
  | "privateCoreOperatorProofSendLinkStatus"
  | "privateCoreOperatorProofSwapLinkStatus"
  | "privateCoreOperatorProofs"
  | "privateCoreOperatorProvingArtifactTruthBasis"
  | "privateCoreOperatorProvingHashLane"
  | "privateCoreOperatorReleaseBoundaryPrimaryNote"
  | "privateCoreOperatorReleaseBoundaryStatusLabel"
  | "privateCoreOperatorReleaseError"
  | "privateCoreOperatorReleases"
  | "privateCoreOperatorRequiredLanesPrimaryNote"
  | "privateCoreOperatorRequiredLanesStatusLabel"
  | "privateCoreOperatorRootCurrentnessLabel"
  | "privateCoreOperatorRootError"
  | "privateCoreOperatorRootRegistrationStatus"
  | "privateCoreOperatorRoots"
  | "privateCoreOperatorSendBoundaryPrimaryNote"
  | "privateCoreOperatorSendBoundaryStatusLabel"
  | "privateCoreOperatorSendContinuityPrimaryNote"
  | "privateCoreOperatorSendContinuityStatusLabel"
  | "privateCoreOperatorSendError"
  | "privateCoreOperatorSendProofError"
  | "privateCoreOperatorSendProofs"
  | "privateCoreOperatorSendResultingRootLinkedProof"
  | "privateCoreOperatorSendResultingRootPrimaryNote"
  | "privateCoreOperatorSendResultingRootProofLinkStatus"
  | "privateCoreOperatorSendResultingRootRecord"
  | "privateCoreOperatorSendResultingRootRegistrationPrimaryNote"
  | "privateCoreOperatorSendResultingRootRegistrationStatusLabel"
  | "privateCoreOperatorSendResultingRootStatusLabel"
  | "privateCoreOperatorSends"
  | "privateCoreOperatorShippingArtifactKind"
  | "privateCoreOperatorShippingArtifactVersion"
  | "privateCoreOperatorShippingDecisionKind"
  | "privateCoreOperatorShippingDecisionVersion"
  | "privateCoreOperatorSnapshotKind"
  | "privateCoreOperatorSnapshotVersion"
  | "privateCoreOperatorSourceArtifactTruthBasis"
  | "privateCoreOperatorSourceProvingRelationship"
  | "privateCoreOperatorStatusKind"
  | "privateCoreOperatorStatusVersion"
  | "privateCoreOperatorSummaryUpdatedAt"
  | "privateCoreOperatorSupportedAssetSymbol"
  | "privateCoreOperatorSupportedEnvironment"
  | "privateCoreOperatorSupportedFlowKind"
  | "privateCoreOperatorSupportedFlowNote"
  | "privateCoreOperatorSupportedFlowStatus"
  | "privateCoreOperatorSupportedFlowVersion"
  | "privateCoreOperatorSupportedNoteSchema"
  | "privateCoreOperatorSupportedNoteVersion"
  | "privateCoreOperatorSupportedProofSystem"
  | "privateCoreOperatorSupportedRecipientModel"
  | "privateCoreOperatorSupportedReleaseAtomicityModel"
  | "privateCoreOperatorSupportedReleaseAuthorizationBasis"
  | "privateCoreOperatorSupportedReleaseCandidateEndpoint"
  | "privateCoreOperatorSupportedReleaseCandidateGateEndpoint"
  | "privateCoreOperatorSupportedReleaseCandidateGateKind"
  | "privateCoreOperatorSupportedReleaseCandidateGateNote"
  | "privateCoreOperatorSupportedReleaseCandidateGateTransport"
  | "privateCoreOperatorSupportedReleaseCandidateGateVersion"
  | "privateCoreOperatorSupportedReleaseCandidateKind"
  | "privateCoreOperatorSupportedReleaseCandidateNote"
  | "privateCoreOperatorSupportedReleaseCandidateTransport"
  | "privateCoreOperatorSupportedReleaseCandidateVersion"
  | "privateCoreOperatorSupportedReleaseDestinationModel"
  | "privateCoreOperatorSupportedReleaseExecutionModel"
  | "privateCoreOperatorSupportedReleaseLaneKind"
  | "privateCoreOperatorSupportedReleaseLaneNote"
  | "privateCoreOperatorSupportedReleaseLaneStatus"
  | "privateCoreOperatorSupportedReleaseLaneVersion"
  | "privateCoreOperatorSupportedReleasePersistenceModel"
  | "privateCoreOperatorSupportedReleaseRootPolicy"
  | "privateCoreOperatorSupportedReleaseV1Decision"
  | "privateCoreOperatorSupportedReleaseV1DecisionNote"
  | "privateCoreOperatorSupportedRootRegistrationProvenance"
  | "privateCoreOperatorSupportedSendCircuit"
  | "privateCoreOperatorSupportedSendInputRootPolicy"
  | "privateCoreOperatorSupportedSendLaneKind"
  | "privateCoreOperatorSupportedSendLaneNote"
  | "privateCoreOperatorSupportedSendLaneStatus"
  | "privateCoreOperatorSupportedSendLaneVersion"
  | "privateCoreOperatorSupportedSendMerkleDepth"
  | "privateCoreOperatorSupportedSendOutputRegistrationPolicy"
  | "privateCoreOperatorSupportedSendResultingRootBasis"
  | "privateCoreOperatorSupportedSendV1Decision"
  | "privateCoreOperatorSupportedSendV1DecisionNote"
  | "privateCoreOperatorSupportedShippingArtifactEndpoint"
  | "privateCoreOperatorSupportedShippingArtifactGateEndpoint"
  | "privateCoreOperatorSupportedShippingArtifactGateKind"
  | "privateCoreOperatorSupportedShippingArtifactGateNote"
  | "privateCoreOperatorSupportedShippingArtifactGateTransport"
  | "privateCoreOperatorSupportedShippingArtifactGateVersion"
  | "privateCoreOperatorSupportedShippingArtifactNote"
  | "privateCoreOperatorSupportedShippingArtifactTransport"
  | "privateCoreOperatorSupportedShippingDecisionEndpoint"
  | "privateCoreOperatorSupportedShippingDecisionGateEndpoint"
  | "privateCoreOperatorSupportedShippingDecisionGateKind"
  | "privateCoreOperatorSupportedShippingDecisionGateNote"
  | "privateCoreOperatorSupportedShippingDecisionGateTransport"
  | "privateCoreOperatorSupportedShippingDecisionGateVersion"
  | "privateCoreOperatorSupportedShippingDecisionNote"
  | "privateCoreOperatorSupportedShippingDecisionTransport"
  | "privateCoreOperatorSupportedSnapshotEndpoint"
  | "privateCoreOperatorSupportedSnapshotGateEndpoint"
  | "privateCoreOperatorSupportedSnapshotGateKind"
  | "privateCoreOperatorSupportedSnapshotGateNote"
  | "privateCoreOperatorSupportedSnapshotGateTransport"
  | "privateCoreOperatorSupportedSnapshotGateVersion"
  | "privateCoreOperatorSupportedSnapshotNote"
  | "privateCoreOperatorSupportedSnapshotTransport"
  | "privateCoreOperatorSupportedStatusEndpoint"
  | "privateCoreOperatorSupportedStatusGateEndpoint"
  | "privateCoreOperatorSupportedStatusGateKind"
  | "privateCoreOperatorSupportedStatusGateNote"
  | "privateCoreOperatorSupportedStatusGateTransport"
  | "privateCoreOperatorSupportedStatusGateVersion"
  | "privateCoreOperatorSupportedStatusNote"
  | "privateCoreOperatorSupportedStatusTransport"
  | "privateCoreOperatorSupportedSwapInputRootPolicy"
  | "privateCoreOperatorSupportedSwapLaneKind"
  | "privateCoreOperatorSupportedSwapLaneNote"
  | "privateCoreOperatorSupportedSwapLaneStatus"
  | "privateCoreOperatorSupportedSwapLaneVersion"
  | "privateCoreOperatorSupportedSwapOutputModel"
  | "privateCoreOperatorSupportedSwapOutputRegistrationPolicy"
  | "privateCoreOperatorSupportedSwapResultingRootBasis"
  | "privateCoreOperatorSupportedSwapV1Decision"
  | "privateCoreOperatorSupportedSwapV1DecisionNote"
  | "privateCoreOperatorSupportedSwapV1Role"
  | "privateCoreOperatorSupportedSwapV1RoleNote"
  | "privateCoreOperatorSupportedSwapVenue"
  | "privateCoreOperatorSupportedUnshieldCircuit"
  | "privateCoreOperatorSupportedUnshieldLaneKind"
  | "privateCoreOperatorSupportedUnshieldLaneNote"
  | "privateCoreOperatorSupportedUnshieldLaneStatus"
  | "privateCoreOperatorSupportedUnshieldLaneVersion"
  | "privateCoreOperatorSupportedUnshieldMerkleDepth"
  | "privateCoreOperatorSupportedUnshieldV1Decision"
  | "privateCoreOperatorSupportedUnshieldV1DecisionNote"
  | "privateCoreOperatorSupportedZkV1RequiredLanes"
  | "privateCoreOperatorSupportedZkV1RequiredLanesNote"
  | "privateCoreOperatorSupportedZkV1ScopeDecision"
  | "privateCoreOperatorSupportedZkV1ScopeNote"
  | "privateCoreOperatorSwapBoundaryPrimaryNote"
  | "privateCoreOperatorSwapBoundaryStatusLabel"
  | "privateCoreOperatorSwapContinuityPrimaryNote"
  | "privateCoreOperatorSwapContinuityStatusLabel"
  | "privateCoreOperatorSwapProofs"
  | "privateCoreOperatorSwapResultingRootLinkedProof"
  | "privateCoreOperatorSwapResultingRootPrimaryNote"
  | "privateCoreOperatorSwapResultingRootProofLinkStatus"
  | "privateCoreOperatorSwapResultingRootRecord"
  | "privateCoreOperatorSwapResultingRootRegistrationPrimaryNote"
  | "privateCoreOperatorSwapResultingRootRegistrationStatusLabel"
  | "privateCoreOperatorSwapResultingRootStatusLabel"
  | "privateCoreOperatorSwaps"
  | "privateCoreOperatorZkV1FinishLinePrimaryNote"
  | "privateCoreOperatorZkV1FinishLineStatusLabel"
  | "privateCoreOperatorZkV1ShippingPrimaryNote"
  | "privateCoreOperatorZkV1ShippingStatusLabel"
  | "privateCoreRecentShield"
  | "privateCoreReleaseCandidateState"
  | "privateCoreReleaseHandoffState"
  | "privateCoreReleasePackageState"
  | "privateCoreReleaseWorkflowState"
  | "privateCoreSendState"
  | "privateCoreSwapState"
  | "privateCoreUnshieldState"
>;

export type BuildPrivateCoreStatePanelOptions = {
  compact?: boolean;
  title: string;
};

export function buildPrivateCoreStatePanelProps(
  bindings: PrivateCoreStatePanelBindings,
  options: BuildPrivateCoreStatePanelOptions,
): VantaPrivateCoreStatePanelProps {
  return {
    compact: options.compact ?? false,
    title: options.title,
    holdState: bindings.privateCoreHoldState,
    releaseCandidateState: bindings.privateCoreReleaseCandidateState,
    releaseHandoffState: bindings.privateCoreReleaseHandoffState,
    releasePackageState: bindings.privateCoreReleasePackageState,
    releaseWorkflowState: bindings.privateCoreReleaseWorkflowState,
    sendState: bindings.privateCoreSendState,
    swapState: bindings.privateCoreSwapState,
    operatorCurrentRoot: bindings.privateCoreOperatorCurrentRoot,
    operatorConsumeError: bindings.privateCoreOperatorConsumeError,
    operatorConsumes: bindings.privateCoreOperatorConsumes,
    operatorLatestConsume: bindings.privateCoreOperatorLatestConsume,
    operatorLatestConsumeProof: bindings.privateCoreOperatorLatestConsumeProof,
    operatorLatestProof: bindings.privateCoreOperatorLatestProof,
    operatorLatestRelease: bindings.privateCoreOperatorLatestRelease,
    operatorLatestReleaseProof: bindings.privateCoreOperatorLatestReleaseProof,
    operatorLatestRoot: bindings.privateCoreOperatorLatestRoot,
    operatorLatestSend: bindings.privateCoreOperatorLatestSend,
    operatorLatestSendLinkedProof: bindings.privateCoreOperatorLatestSendLinkedProof,
    operatorLatestSendProof: bindings.privateCoreOperatorLatestSendProof,
    operatorLatestSwap: bindings.privateCoreOperatorLatestSwap,
    operatorLatestSwapLinkedProof: bindings.privateCoreOperatorLatestSwapLinkedProof,
    operatorLatestSwapProof: bindings.privateCoreOperatorLatestSwapProof,
    operatorBoundaryPrimaryNote: bindings.privateCoreOperatorBoundaryPrimaryNote,
    operatorBoundaryStatusLabel: bindings.privateCoreOperatorBoundaryStatusLabel,
    operatorContractMirrorPrimaryNote: bindings.privateCoreOperatorContractMirrorPrimaryNote,
    operatorContractMirrorStatusLabel: bindings.privateCoreOperatorContractMirrorStatusLabel,
    operatorReleaseBoundaryPrimaryNote: bindings.privateCoreOperatorReleaseBoundaryPrimaryNote,
    operatorReleaseBoundaryStatusLabel: bindings.privateCoreOperatorReleaseBoundaryStatusLabel,
    operatorRequiredLanesPrimaryNote: bindings.privateCoreOperatorRequiredLanesPrimaryNote,
    operatorRequiredLanesStatusLabel: bindings.privateCoreOperatorRequiredLanesStatusLabel,
    operatorZkV1ShippingPrimaryNote: bindings.privateCoreOperatorZkV1ShippingPrimaryNote,
    operatorZkV1ShippingStatusLabel: bindings.privateCoreOperatorZkV1ShippingStatusLabel,
    operatorSendBoundaryPrimaryNote: bindings.privateCoreOperatorSendBoundaryPrimaryNote,
    operatorSendBoundaryStatusLabel: bindings.privateCoreOperatorSendBoundaryStatusLabel,
    operatorSendContinuityPrimaryNote: bindings.privateCoreOperatorSendContinuityPrimaryNote,
    operatorSendContinuityStatusLabel: bindings.privateCoreOperatorSendContinuityStatusLabel,
    operatorSwapBoundaryPrimaryNote: bindings.privateCoreOperatorSwapBoundaryPrimaryNote,
    operatorSwapBoundaryStatusLabel: bindings.privateCoreOperatorSwapBoundaryStatusLabel,
    operatorSwapContinuityPrimaryNote: bindings.privateCoreOperatorSwapContinuityPrimaryNote,
    operatorSwapContinuityStatusLabel: bindings.privateCoreOperatorSwapContinuityStatusLabel,
    operatorSupportedSendLaneKind: bindings.privateCoreOperatorSupportedSendLaneKind,
    operatorSupportedSendLaneNote: bindings.privateCoreOperatorSupportedSendLaneNote,
    operatorSupportedSendLaneStatus: bindings.privateCoreOperatorSupportedSendLaneStatus,
    operatorSupportedSendLaneVersion: bindings.privateCoreOperatorSupportedSendLaneVersion,
    operatorSupportedSendV1Decision: bindings.privateCoreOperatorSupportedSendV1Decision,
    operatorSupportedSendV1DecisionNote: bindings.privateCoreOperatorSupportedSendV1DecisionNote,
    operatorSupportedUnshieldLaneKind: bindings.privateCoreOperatorSupportedUnshieldLaneKind,
    operatorSupportedUnshieldLaneNote: bindings.privateCoreOperatorSupportedUnshieldLaneNote,
    operatorSupportedUnshieldLaneStatus: bindings.privateCoreOperatorSupportedUnshieldLaneStatus,
    operatorSupportedUnshieldLaneVersion: bindings.privateCoreOperatorSupportedUnshieldLaneVersion,
    operatorSupportedUnshieldV1Decision: bindings.privateCoreOperatorSupportedUnshieldV1Decision,
    operatorSupportedUnshieldV1DecisionNote: bindings.privateCoreOperatorSupportedUnshieldV1DecisionNote,
    operatorSupportedReleaseLaneKind: bindings.privateCoreOperatorSupportedReleaseLaneKind,
    operatorSupportedReleaseLaneNote: bindings.privateCoreOperatorSupportedReleaseLaneNote,
    operatorSupportedReleaseLaneStatus: bindings.privateCoreOperatorSupportedReleaseLaneStatus,
    operatorSupportedReleaseLaneVersion: bindings.privateCoreOperatorSupportedReleaseLaneVersion,
    operatorSupportedSwapLaneKind: bindings.privateCoreOperatorSupportedSwapLaneKind,
    operatorSupportedSwapLaneNote: bindings.privateCoreOperatorSupportedSwapLaneNote,
    operatorSupportedSwapLaneStatus: bindings.privateCoreOperatorSupportedSwapLaneStatus,
    operatorSupportedSwapLaneVersion: bindings.privateCoreOperatorSupportedSwapLaneVersion,
    operatorSupportedSwapV1Decision: bindings.privateCoreOperatorSupportedSwapV1Decision,
    operatorSupportedSwapV1DecisionNote: bindings.privateCoreOperatorSupportedSwapV1DecisionNote,
    operatorSupportedSwapV1Role: bindings.privateCoreOperatorSupportedSwapV1Role,
    operatorSupportedSwapV1RoleNote: bindings.privateCoreOperatorSupportedSwapV1RoleNote,
    operatorSupportedSwapVenue: bindings.privateCoreOperatorSupportedSwapVenue,
    operatorSupportedSwapOutputModel: bindings.privateCoreOperatorSupportedSwapOutputModel,
    operatorSupportedSwapResultingRootBasis: bindings.privateCoreOperatorSupportedSwapResultingRootBasis,
    operatorSupportedSwapInputRootPolicy: bindings.privateCoreOperatorSupportedSwapInputRootPolicy,
    operatorSupportedSwapOutputRegistrationPolicy: bindings.privateCoreOperatorSupportedSwapOutputRegistrationPolicy,
    operatorSupportedReleaseV1Decision: bindings.privateCoreOperatorSupportedReleaseV1Decision,
    operatorSupportedReleaseV1DecisionNote: bindings.privateCoreOperatorSupportedReleaseV1DecisionNote,
    operatorSupportedFlowKind: bindings.privateCoreOperatorSupportedFlowKind,
    operatorSupportedFlowNote: bindings.privateCoreOperatorSupportedFlowNote,
    operatorSupportedFlowStatus: bindings.privateCoreOperatorSupportedFlowStatus,
    operatorSupportedFlowVersion: bindings.privateCoreOperatorSupportedFlowVersion,
    operatorSupportedZkV1ScopeDecision: bindings.privateCoreOperatorSupportedZkV1ScopeDecision,
    operatorSupportedZkV1ScopeNote: bindings.privateCoreOperatorSupportedZkV1ScopeNote,
    operatorSupportedZkV1RequiredLanes: bindings.privateCoreOperatorSupportedZkV1RequiredLanes,
    operatorSupportedZkV1RequiredLanesNote: bindings.privateCoreOperatorSupportedZkV1RequiredLanesNote,
    operatorZkV1FinishLineStatusLabel: bindings.privateCoreOperatorZkV1FinishLineStatusLabel,
    operatorZkV1FinishLinePrimaryNote: bindings.privateCoreOperatorZkV1FinishLinePrimaryNote,
    operatorSupportedAssetSymbol: bindings.privateCoreOperatorSupportedAssetSymbol,
    operatorSupportedEnvironment: bindings.privateCoreOperatorSupportedEnvironment,
    operatorSupportedNoteSchema: bindings.privateCoreOperatorSupportedNoteSchema,
    operatorSupportedNoteVersion: bindings.privateCoreOperatorSupportedNoteVersion,
    operatorSupportedRootRegistrationProvenance: bindings.privateCoreOperatorSupportedRootRegistrationProvenance,
    operatorSupportedSendResultingRootBasis: bindings.privateCoreOperatorSupportedSendResultingRootBasis,
    operatorSupportedSendInputRootPolicy: bindings.privateCoreOperatorSupportedSendInputRootPolicy,
    operatorSupportedSendOutputRegistrationPolicy: bindings.privateCoreOperatorSupportedSendOutputRegistrationPolicy,
    operatorSupportedRecipientModel: bindings.privateCoreOperatorSupportedRecipientModel,
    operatorSupportedReleaseDestinationModel: bindings.privateCoreOperatorSupportedReleaseDestinationModel,
    operatorSupportedProofSystem: bindings.privateCoreOperatorSupportedProofSystem,
    operatorSupportedUnshieldCircuit: bindings.privateCoreOperatorSupportedUnshieldCircuit,
    operatorSupportedSendCircuit: bindings.privateCoreOperatorSupportedSendCircuit,
    operatorSupportedUnshieldMerkleDepth: bindings.privateCoreOperatorSupportedUnshieldMerkleDepth,
    operatorSupportedSendMerkleDepth: bindings.privateCoreOperatorSupportedSendMerkleDepth,
    operatorSupportedReleaseAuthorizationBasis: bindings.privateCoreOperatorSupportedReleaseAuthorizationBasis,
    operatorSupportedReleaseRootPolicy: bindings.privateCoreOperatorSupportedReleaseRootPolicy,
    operatorSupportedReleaseExecutionModel: bindings.privateCoreOperatorSupportedReleaseExecutionModel,
    operatorSupportedReleaseAtomicityModel: bindings.privateCoreOperatorSupportedReleaseAtomicityModel,
    operatorSupportedReleasePersistenceModel: bindings.privateCoreOperatorSupportedReleasePersistenceModel,
    operatorOwnerAuthorizationMode: bindings.privateCoreOperatorOwnerAuthorizationMode,
    operatorOwnerAuthorizationDecision: bindings.privateCoreOperatorOwnerAuthorizationDecision,
    operatorOwnerAuthorizationDecisionNote: bindings.privateCoreOperatorOwnerAuthorizationDecisionNote,
    operatorSourceArtifactTruthBasis: bindings.privateCoreOperatorSourceArtifactTruthBasis,
    operatorProvingArtifactTruthBasis: bindings.privateCoreOperatorProvingArtifactTruthBasis,
    operatorSourceProvingRelationship: bindings.privateCoreOperatorSourceProvingRelationship,
    operatorNullifierKeyMode: bindings.privateCoreOperatorNullifierKeyMode,
    operatorProvingHashLane: bindings.privateCoreOperatorProvingHashLane,
    operatorCurrentRootLinkedProof: bindings.privateCoreOperatorCurrentRootLinkedProof,
    operatorCurrentRootProofLinkStatus: bindings.privateCoreOperatorCurrentRootProofLinkStatus,
    operatorSendResultingRootLinkedProof: bindings.privateCoreOperatorSendResultingRootLinkedProof,
    operatorSendResultingRootRecord: bindings.privateCoreOperatorSendResultingRootRecord,
    operatorSendResultingRootPrimaryNote: bindings.privateCoreOperatorSendResultingRootPrimaryNote,
    operatorSendResultingRootRegistrationPrimaryNote: bindings.privateCoreOperatorSendResultingRootRegistrationPrimaryNote,
    operatorSendResultingRootRegistrationStatusLabel: bindings.privateCoreOperatorSendResultingRootRegistrationStatusLabel,
    operatorSendResultingRootProofLinkStatus: bindings.privateCoreOperatorSendResultingRootProofLinkStatus,
    operatorSendResultingRootStatusLabel: bindings.privateCoreOperatorSendResultingRootStatusLabel,
    operatorSwapResultingRootLinkedProof: bindings.privateCoreOperatorSwapResultingRootLinkedProof,
    operatorSwapResultingRootRecord: bindings.privateCoreOperatorSwapResultingRootRecord,
    operatorSwapResultingRootPrimaryNote: bindings.privateCoreOperatorSwapResultingRootPrimaryNote,
    operatorSwapResultingRootRegistrationPrimaryNote: bindings.privateCoreOperatorSwapResultingRootRegistrationPrimaryNote,
    operatorSwapResultingRootRegistrationStatusLabel: bindings.privateCoreOperatorSwapResultingRootRegistrationStatusLabel,
    operatorSwapResultingRootProofLinkStatus: bindings.privateCoreOperatorSwapResultingRootProofLinkStatus,
    operatorSwapResultingRootStatusLabel: bindings.privateCoreOperatorSwapResultingRootStatusLabel,
    operatorProofConsumeLinkStatus: bindings.privateCoreOperatorProofConsumeLinkStatus,
    operatorProofError: bindings.privateCoreOperatorProofError,
    operatorProofs: bindings.privateCoreOperatorProofs,
    operatorProofSendLinkStatus: bindings.privateCoreOperatorProofSendLinkStatus,
    operatorProofSwapLinkStatus: bindings.privateCoreOperatorProofSwapLinkStatus,
    operatorProofReleaseLinkStatus: bindings.privateCoreOperatorProofReleaseLinkStatus,
    operatorReleaseError: bindings.privateCoreOperatorReleaseError,
    operatorReleases: bindings.privateCoreOperatorReleases,
    operatorRootCurrentnessLabel: bindings.privateCoreOperatorRootCurrentnessLabel,
    operatorRootError: bindings.privateCoreOperatorRootError,
    operatorRootRegistrationStatus: bindings.privateCoreOperatorRootRegistrationStatus,
    operatorRoots: bindings.privateCoreOperatorRoots,
    operatorContractStateVersion: bindings.privateCoreOperatorContractStateVersion,
    operatorContractVersion: bindings.privateCoreOperatorContractVersion,
    operatorContractSummaryVersion: bindings.privateCoreOperatorContractSummaryVersion,
    operatorStatusVersion: bindings.privateCoreOperatorStatusVersion,
    operatorStatusKind: bindings.privateCoreOperatorStatusKind,
    operatorSnapshotVersion: bindings.privateCoreOperatorSnapshotVersion,
    operatorSnapshotKind: bindings.privateCoreOperatorSnapshotKind,
    operatorSupportedStatusNote: bindings.privateCoreOperatorSupportedStatusNote,
    operatorSupportedStatusTransport: bindings.privateCoreOperatorSupportedStatusTransport,
    operatorSupportedStatusEndpoint: bindings.privateCoreOperatorSupportedStatusEndpoint,
    operatorSupportedStatusGateVersion: bindings.privateCoreOperatorSupportedStatusGateVersion,
    operatorSupportedStatusGateKind: bindings.privateCoreOperatorSupportedStatusGateKind,
    operatorSupportedStatusGateNote: bindings.privateCoreOperatorSupportedStatusGateNote,
    operatorSupportedStatusGateTransport: bindings.privateCoreOperatorSupportedStatusGateTransport,
    operatorSupportedStatusGateEndpoint: bindings.privateCoreOperatorSupportedStatusGateEndpoint,
    operatorSupportedSnapshotGateVersion: bindings.privateCoreOperatorSupportedSnapshotGateVersion,
    operatorSupportedSnapshotGateKind: bindings.privateCoreOperatorSupportedSnapshotGateKind,
    operatorSupportedSnapshotGateNote: bindings.privateCoreOperatorSupportedSnapshotGateNote,
    operatorSupportedSnapshotGateTransport: bindings.privateCoreOperatorSupportedSnapshotGateTransport,
    operatorSupportedSnapshotGateEndpoint: bindings.privateCoreOperatorSupportedSnapshotGateEndpoint,
    operatorSupportedShippingDecisionGateVersion: bindings.privateCoreOperatorSupportedShippingDecisionGateVersion,
    operatorSupportedShippingDecisionGateKind: bindings.privateCoreOperatorSupportedShippingDecisionGateKind,
    operatorSupportedShippingDecisionGateNote: bindings.privateCoreOperatorSupportedShippingDecisionGateNote,
    operatorSupportedShippingDecisionGateTransport: bindings.privateCoreOperatorSupportedShippingDecisionGateTransport,
    operatorSupportedShippingDecisionGateEndpoint: bindings.privateCoreOperatorSupportedShippingDecisionGateEndpoint,
    operatorSupportedShippingDecisionTransport: bindings.privateCoreOperatorSupportedShippingDecisionTransport,
    operatorSupportedShippingDecisionEndpoint: bindings.privateCoreOperatorSupportedShippingDecisionEndpoint,
    operatorSupportedShippingArtifactGateVersion: bindings.privateCoreOperatorSupportedShippingArtifactGateVersion,
    operatorSupportedShippingArtifactGateKind: bindings.privateCoreOperatorSupportedShippingArtifactGateKind,
    operatorSupportedShippingArtifactGateNote: bindings.privateCoreOperatorSupportedShippingArtifactGateNote,
    operatorSupportedShippingArtifactGateTransport: bindings.privateCoreOperatorSupportedShippingArtifactGateTransport,
    operatorSupportedShippingArtifactGateEndpoint: bindings.privateCoreOperatorSupportedShippingArtifactGateEndpoint,
    operatorSupportedSnapshotNote: bindings.privateCoreOperatorSupportedSnapshotNote,
    operatorSupportedSnapshotTransport: bindings.privateCoreOperatorSupportedSnapshotTransport,
    operatorSupportedSnapshotEndpoint: bindings.privateCoreOperatorSupportedSnapshotEndpoint,
    operatorSupportedShippingArtifactNote: bindings.privateCoreOperatorSupportedShippingArtifactNote,
    operatorSupportedShippingArtifactTransport: bindings.privateCoreOperatorSupportedShippingArtifactTransport,
    operatorSupportedShippingArtifactEndpoint: bindings.privateCoreOperatorSupportedShippingArtifactEndpoint,
    operatorSupportedReleaseCandidateVersion: bindings.privateCoreOperatorSupportedReleaseCandidateVersion,
    operatorSupportedReleaseCandidateKind: bindings.privateCoreOperatorSupportedReleaseCandidateKind,
    operatorSupportedReleaseCandidateNote: bindings.privateCoreOperatorSupportedReleaseCandidateNote,
    operatorSupportedReleaseCandidateGateVersion: bindings.privateCoreOperatorSupportedReleaseCandidateGateVersion,
    operatorSupportedReleaseCandidateGateKind: bindings.privateCoreOperatorSupportedReleaseCandidateGateKind,
    operatorSupportedReleaseCandidateGateNote: bindings.privateCoreOperatorSupportedReleaseCandidateGateNote,
    operatorSupportedReleaseCandidateGateTransport: bindings.privateCoreOperatorSupportedReleaseCandidateGateTransport,
    operatorSupportedReleaseCandidateGateEndpoint: bindings.privateCoreOperatorSupportedReleaseCandidateGateEndpoint,
    operatorSupportedReleaseCandidateTransport: bindings.privateCoreOperatorSupportedReleaseCandidateTransport,
    operatorSupportedReleaseCandidateEndpoint: bindings.privateCoreOperatorSupportedReleaseCandidateEndpoint,
    operatorShippingArtifactVersion: bindings.privateCoreOperatorShippingArtifactVersion,
    operatorShippingArtifactKind: bindings.privateCoreOperatorShippingArtifactKind,
    operatorShippingDecisionVersion: bindings.privateCoreOperatorShippingDecisionVersion,
    operatorShippingDecisionKind: bindings.privateCoreOperatorShippingDecisionKind,
    operatorSupportedShippingDecisionNote: bindings.privateCoreOperatorSupportedShippingDecisionNote,
    operatorSendError: bindings.privateCoreOperatorSendError,
    operatorSends: bindings.privateCoreOperatorSends,
    operatorSendProofError: bindings.privateCoreOperatorSendProofError,
    operatorSendProofs: bindings.privateCoreOperatorSendProofs,
    operatorSwaps: bindings.privateCoreOperatorSwaps,
    operatorSwapProofs: bindings.privateCoreOperatorSwapProofs,
    operatorSummaryUpdatedAt: bindings.privateCoreOperatorSummaryUpdatedAt,
    shieldState: bindings.privateCoreRecentShield,
    unshieldState: bindings.privateCoreUnshieldState,
  };
}
