/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_SOLANA_RPC_URL?: string;
  readonly VITE_SOLANA_READ_RPC_FALLBACK_URLS?: string;
  readonly VITE_SOLANA_WS_URL?: string;
  readonly VITE_SOLANA_CLUSTER?: string;
  readonly VITE_VANTA_VAULT_DERIVATION_PROGRAM_ID?: string;
  readonly VITE_VANTA_MAINNET_TOKEN_MINT?: string;
  readonly VITE_VANTA_MAINNET_USDC_MINT?: string;
  readonly VITE_VANTA_MAINNET_JTO_MINT?: string;
  readonly VITE_VANTA_MAINNET_BONK_MINT?: string;
  readonly VITE_VANTA_MAINNET_JUP_MINT?: string;
  readonly VITE_VANTA_MAINNET_PYUSD_MINT?: string;
  readonly VITE_VANTA_MAINNET_WIF_MINT?: string;
  readonly VITE_VANTA_MAINNET_KMNO_MINT?: string;
  readonly VITE_VANTA_MAINNET_VAULT_OWNER?: string;
  readonly VITE_VANTA_MAINNET_TOKEN_NAME?: string;
  readonly VITE_VANTA_MAINNET_USDC_NAME?: string;
  readonly VITE_VANTA_MAINNET_JTO_NAME?: string;
  readonly VITE_VANTA_MAINNET_BONK_NAME?: string;
  readonly VITE_VANTA_MAINNET_JUP_NAME?: string;
  readonly VITE_VANTA_MAINNET_PYUSD_NAME?: string;
  readonly VITE_VANTA_MAINNET_WIF_NAME?: string;
  readonly VITE_VANTA_MAINNET_KMNO_NAME?: string;
  readonly VITE_VANTA_MAINNET_TOKEN_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_USDC_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_JTO_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_BONK_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_JUP_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_PYUSD_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_WIF_DECIMALS?: string;
  readonly VITE_VANTA_MAINNET_KMNO_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_TOKEN_MINT?: string;
  readonly VITE_VANTA_DEVNET_USDC_MINT?: string;
  readonly VITE_VANTA_DEVNET_JTO_MINT?: string;
  readonly VITE_VANTA_DEVNET_BONK_MINT?: string;
  readonly VITE_VANTA_DEVNET_JUP_MINT?: string;
  readonly VITE_VANTA_DEVNET_PYUSD_MINT?: string;
  readonly VITE_VANTA_DEVNET_WIF_MINT?: string;
  readonly VITE_VANTA_DEVNET_KMNO_MINT?: string;
  readonly VITE_VANTA_DEVNET_VAULT_OWNER?: string;
  readonly VITE_VANTA_DEVNET_TOKEN_NAME?: string;
  readonly VITE_VANTA_DEVNET_USDC_NAME?: string;
  readonly VITE_VANTA_DEVNET_JTO_NAME?: string;
  readonly VITE_VANTA_DEVNET_BONK_NAME?: string;
  readonly VITE_VANTA_DEVNET_JUP_NAME?: string;
  readonly VITE_VANTA_DEVNET_PYUSD_NAME?: string;
  readonly VITE_VANTA_DEVNET_WIF_NAME?: string;
  readonly VITE_VANTA_DEVNET_KMNO_NAME?: string;
  readonly VITE_VANTA_DEVNET_TOKEN_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_USDC_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_JTO_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_BONK_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_JUP_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_PYUSD_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_WIF_DECIMALS?: string;
  readonly VITE_VANTA_DEVNET_KMNO_DECIMALS?: string;
  readonly VITE_VANTA_UNSHIELD_OPERATOR_URL?: string;
  readonly VITE_VANTA_SWAP_OPERATOR_URL?: string;
  readonly VITE_VANTA_SOL_TO_SHIELDED_SWAP_OPERATOR_URL?: string;
  readonly VITE_VANTA_SOL_UNSHIELD_OPERATOR_URL?: string;
  readonly VITE_VANTA_METEORA_DLMM_POOL_ADDRESS?: string;
  readonly VITE_VANTA_ENABLE_PEER_ONRAMP?: string;
  readonly VITE_VANTA_ENABLE_LIVE_PEER_FUNDING?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
